import {
  User,
  UserCredential,
  EmployeeProfile,
  EmploymentDetails,
  Task,
  TaskUpdate,
  WorkHour,
  EmployeeDocument,
  Announcement,
  Message,
  RoadmapItem,
  FinanceTransaction,
  GrowthMetric,
  BalanceSheetEntry,
  AuditLog
} from '../types';
import { hashPassword } from './cryptoUtils';

export const SEED_SALT = 'ApexSalt2026Secure';
export const SEED_DEFAULT_HASH = hashPassword('Password@123', SEED_SALT);

export const initialCredentials: UserCredential[] = [
  {
    userId: 'usr_founder',
    email: 'shwetha@apextech.io',
    salt: SEED_SALT,
    passwordHash: SEED_DEFAULT_HASH,
  },
  {
    userId: 'usr_emp_1',
    email: 'david.miller@apextech.io',
    salt: SEED_SALT,
    passwordHash: SEED_DEFAULT_HASH,
  },
  {
    userId: 'usr_emp_2',
    email: 'elena.rostova@apextech.io',
    salt: SEED_SALT,
    passwordHash: SEED_DEFAULT_HASH,
  },
  {
    userId: 'usr_emp_3',
    email: 'marcus.chen@apextech.io',
    salt: SEED_SALT,
    passwordHash: SEED_DEFAULT_HASH,
  },
];

export const initialUsers: User[] = [
  {
    id: 'usr_founder',
    email: 'shwetha@apextech.io',
    personalEmail: 'shwetha.founder@gmail.com',
    name: 'Shwetha',
    role: 'FOUNDER_DIRECTOR',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-09 09:30',
    department: 'Executive Leadership',
    designation: 'Managing Director & Admin',
  },
  {
    id: 'usr_emp_1',
    email: 'david.miller@apextech.io',
    personalEmail: 'david.miller.personal@gmail.com',
    name: 'David Miller',
    role: 'EMPLOYEE',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-08 19:15',
    department: 'Engineering',
    designation: 'Lead Full-Stack Developer',
  },
  {
    id: 'usr_emp_2',
    email: 'elena.rostova@apextech.io',
    personalEmail: 'elena.rostova.design@gmail.com',
    name: 'Elena Rostova',
    role: 'EMPLOYEE',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-08 17:30',
    department: 'Design',
    designation: 'Staff Product Designer',
  },
  {
    id: 'usr_emp_3',
    email: 'marcus.chen@apextech.io',
    personalEmail: 'marcus.chen.ops@gmail.com',
    name: 'Marcus Chen',
    role: 'EMPLOYEE',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-08 18:05',
    department: 'Operations & Finance',
    designation: 'Operations Coordinator',
  },
];

export const initialProfiles: Record<string, EmployeeProfile> = {
  usr_emp_1: {
    userId: 'usr_emp_1',
    employeeId: 'EMP-1002',
    name: 'David Miller',
    email: 'david.miller@apextech.io',
    personalEmail: 'david.miller.personal@gmail.com',
    phone: '+1 (555) 432-8921',
    address: '742 Evergreen Terrace, Seattle, WA',
    emergencyContact: {
      name: 'Claire Miller',
      relationship: 'Spouse',
      phone: '+1 (555) 887-1234',
    },
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  usr_emp_2: {
    userId: 'usr_emp_2',
    employeeId: 'EMP-1003',
    name: 'Elena Rostova',
    email: 'elena.rostova@apextech.io',
    personalEmail: 'elena.rostova.design@gmail.com',
    phone: '+1 (555) 765-4321',
    address: '1849 Pine Street, San Francisco, CA',
    emergencyContact: {
      name: 'Mikhail Rostov',
      relationship: 'Parent',
      phone: '+1 (555) 321-9876',
    },
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  usr_emp_3: {
    userId: 'usr_emp_3',
    employeeId: 'EMP-1004',
    name: 'Marcus Chen',
    email: 'marcus.chen@apextech.io',
    personalEmail: 'marcus.chen.ops@gmail.com',
    phone: '+1 (555) 678-1234',
    address: '420 Madison Avenue, New York, NY',
    emergencyContact: {
      name: 'Lillian Chen',
      relationship: 'Sibling',
      phone: '+1 (555) 998-7765',
    },
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  usr_founder: {
    userId: 'usr_founder',
    employeeId: 'EMP-1001',
    name: 'Shwetha',
    email: 'shwetha@apextech.io',
    personalEmail: 'shwetha.founder@gmail.com',
    phone: '+1 (555) 234-5678',
    address: '100 Executive Boulevard, Tech Park',
    emergencyContact: {
      name: 'Family Contact',
      relationship: 'Relative',
      phone: '+1 (555) 998-3321',
    },
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
};

export const initialEmploymentDetails: Record<string, EmploymentDetails> = {
  usr_emp_1: {
    employeeId: 'EMP-1002',
    joiningDate: '2024-03-15',
    designation: 'Lead Full-Stack Developer',
    department: 'Engineering',
    reportingPerson: 'Shwetha (Managing Director)',
    employmentStatus: 'Full-Time',
    compensation: '$135,000 / annum',
    bankAccountMasked: '•••• •••• •••• 6421',
    taxIdentifier: 'SSN-•••-••-8910',
    lastReviewDate: '2026-06-30',
  },
  usr_emp_2: {
    employeeId: 'EMP-1003',
    joiningDate: '2024-06-01',
    designation: 'Staff Product Designer',
    department: 'Design',
    reportingPerson: 'Shwetha (Managing Director)',
    employmentStatus: 'Full-Time',
    compensation: '$128,000 / annum',
    bankAccountMasked: '•••• •••• •••• 9923',
    taxIdentifier: 'SSN-•••-••-4521',
    lastReviewDate: '2026-05-15',
  },
  usr_emp_3: {
    employeeId: 'EMP-1004',
    joiningDate: '2024-09-01',
    designation: 'Operations Coordinator',
    department: 'Operations & Finance',
    reportingPerson: 'Shwetha (Managing Director)',
    employmentStatus: 'Probation',
    compensation: '$95,000 / annum',
    bankAccountMasked: '•••• •••• •••• 3341',
    taxIdentifier: 'SSN-•••-••-1120',
    lastReviewDate: '2026-08-01',
  },
  usr_founder: {
    employeeId: 'EMP-1001',
    joiningDate: '2023-01-10',
    designation: 'Managing Director & Founder',
    department: 'Executive Leadership',
    reportingPerson: 'Board of Directors',
    employmentStatus: 'Full-Time',
    compensation: '$160,000 / annum',
    bankAccountMasked: '•••• •••• •••• 1001',
    taxIdentifier: 'EIN-•••-••-1234',
    lastReviewDate: '2026-01-15',
  },
};

export const initialTasks: Task[] = [
  {
    id: 'tsk_101',
    title: 'Migrate Core Authentication to Multi-Factor Auth (MFA)',
    description: 'Implement TOTP authenticator app support and backup recovery codes to satisfy enterprise security audits.',
    assigneeId: 'usr_emp_1',
    assigneeName: 'David Miller',
    creatorId: 'usr_founder',
    priority: 'high',
    status: 'in_progress',
    assignedDate: '2026-09-01',
    dueDate: '2026-09-15',
    progress: 65,
  },
  {
    id: 'tsk_102',
    title: 'Implement Encrypted S3 Document Storage Handler',
    description: 'Create server-side presigned URL generator for sensitive employee ID proof downloads.',
    assigneeId: 'usr_emp_1',
    assigneeName: 'David Miller',
    creatorId: 'usr_founder',
    priority: 'urgent',
    status: 'completed',
    assignedDate: '2026-08-20',
    dueDate: '2026-09-05',
    progress: 100,
    completedAt: '2026-09-04 16:45',
    completionNotes: 'All unit tests passing, signed URL expiration set to 15 minutes as per compliance rule.',
  },
  {
    id: 'tsk_103',
    title: 'Design Dark Mode System for Client Customizer',
    description: 'Deliver high-fidelity Figma components for theme color overrides and contrast ratios.',
    assigneeId: 'usr_emp_2',
    assigneeName: 'Elena Rostova',
    creatorId: 'usr_founder',
    priority: 'medium',
    status: 'in_progress',
    assignedDate: '2026-09-02',
    dueDate: '2026-09-18',
    progress: 40,
  },
  {
    id: 'tsk_104',
    title: 'Q3 Financial Reconciliation & Vendor Invoices',
    description: 'Cross-check AWS hosting charges and contractor disbursements against approved quarterly budget.',
    assigneeId: 'usr_emp_3',
    assigneeName: 'Marcus Chen',
    creatorId: 'usr_founder',
    priority: 'high',
    status: 'blocked',
    assignedDate: '2026-09-05',
    dueDate: '2026-09-12',
    progress: 25,
  },
  {
    id: 'tsk_105',
    title: 'Prepare ISO-27001 Policy Documentation Center',
    description: 'Review updated workplace conduct and data handling policies with outside legal counsel.',
    assigneeId: 'usr_emp_1',
    assigneeName: 'David Miller',
    creatorId: 'usr_founder',
    priority: 'low',
    status: 'not_started',
    assignedDate: '2026-09-08',
    dueDate: '2026-09-30',
    progress: 0,
  },
];

export const initialTaskUpdates: Record<string, TaskUpdate[]> = {
  tsk_101: [
    {
      id: 'upd_1',
      taskId: 'tsk_101',
      authorName: 'David Miller',
      updateText: 'Completed TOTP secret generation and QR code verification endpoint.',
      progress: 40,
      timestamp: '2026-09-04 14:10',
    },
    {
      id: 'upd_2',
      taskId: 'tsk_101',
      authorName: 'David Miller',
      updateText: 'Currently hooking backup recovery codes into secure encrypted user vault.',
      progress: 65,
      timestamp: '2026-09-08 11:30',
    },
  ],
};

export const initialWorkHours: WorkHour[] = [
  {
    id: 'wh_1',
    employeeId: 'usr_emp_1',
    employeeName: 'David Miller',
    date: '2026-09-08',
    clockIn: '09:00 AM',
    clockOut: '05:30 PM',
    totalHours: 8.5,
    status: 'approved',
    recordingMethod: 'clock_in_out',
    approvedBy: 'Shwetha (Managing Director)',
    approvedAt: '2026-09-08 18:00',
    notes: 'Auth MFA backend tasks and architecture code reviews',
  },
  {
    id: 'wh_2',
    employeeId: 'usr_emp_1',
    employeeName: 'David Miller',
    date: '2026-09-07',
    clockIn: '08:45 AM',
    clockOut: '05:15 PM',
    totalHours: 8.5,
    status: 'approved',
    recordingMethod: 'clock_in_out',
    approvedBy: 'Shwetha (Managing Director)',
    approvedAt: '2026-09-07 17:45',
    notes: 'Sprint planning and S3 upload security verification',
  },
  {
    id: 'wh_3',
    employeeId: 'usr_emp_1',
    employeeName: 'David Miller',
    date: '2026-09-09',
    clockIn: '09:15 AM',
    clockOut: '06:00 PM',
    totalHours: 8.75,
    status: 'pending',
    recordingMethod: 'manual',
    notes: 'Task status updates and backend validation endpoints',
  },
  {
    id: 'wh_4',
    employeeId: 'usr_emp_2',
    employeeName: 'Elena Rostova',
    date: '2026-09-08',
    clockIn: '09:30 AM',
    clockOut: '06:00 PM',
    totalHours: 8.5,
    status: 'approved',
    recordingMethod: 'clock_in_out',
    approvedBy: 'Shwetha (Managing Director)',
    approvedAt: '2026-09-08 18:15',
    notes: 'Figma UI design system token review and mobile prototypes',
  },
  {
    id: 'wh_5',
    employeeId: 'usr_emp_2',
    employeeName: 'Elena Rostova',
    date: '2026-09-09',
    clockIn: '09:00 AM',
    clockOut: '05:00 PM',
    totalHours: 8.0,
    status: 'pending',
    recordingMethod: 'timesheet',
    notes: 'Design review on executive dashboard widgets and color tokens',
  },
  {
    id: 'wh_6',
    employeeId: 'usr_emp_3',
    employeeName: 'Marcus Chen',
    date: '2026-09-08',
    clockIn: '08:30 AM',
    clockOut: '05:00 PM',
    totalHours: 8.5,
    status: 'approved',
    recordingMethod: 'clock_in_out',
    approvedBy: 'Shwetha (Managing Director)',
    approvedAt: '2026-09-08 17:30',
    notes: 'Operations ledger checks and quarterly expense audit',
  },
  {
    id: 'wh_7',
    employeeId: 'usr_emp_3',
    employeeName: 'Marcus Chen',
    date: '2026-09-09',
    clockIn: '09:00 AM',
    clockOut: '05:30 PM',
    totalHours: 8.5,
    status: 'pending',
    recordingMethod: 'manual',
    notes: 'Vendor reconciliation and tax declaration filings',
  },
];

export const initialDocuments: EmployeeDocument[] = [
  {
    id: 'doc_1',
    employeeId: 'usr_emp_1',
    category: 'Offer Letter',
    name: 'Employment Offer & Compensation Package',
    fileName: 'OfferLetter_DavidMiller_Signed.pdf',
    fileSize: '1.4 MB',
    uploadDate: '2024-03-12',
    version: 'v1.0 (Countersigned)',
    uploaderName: 'Sarah Jenkins (Founder)',
    privateUrl: '#',
  },
  {
    id: 'doc_2',
    employeeId: 'usr_emp_1',
    category: 'ID Proofs',
    name: 'Government ID & Passport Verification',
    fileName: 'Govt_Passport_Copy_Encrypted.pdf',
    fileSize: '2.8 MB',
    uploadDate: '2024-03-14',
    version: 'v1.0',
    uploaderName: 'David Miller',
    privateUrl: '#',
  },
  {
    id: 'doc_3',
    employeeId: 'usr_emp_1',
    category: 'Policies',
    name: 'Employee Handbook & Code of Professional Conduct',
    fileName: 'Handbook_Policies_2026.pdf',
    fileSize: '3.2 MB',
    uploadDate: '2026-01-05',
    version: 'v2.4',
    uploaderName: 'Sarah Jenkins (Founder)',
    privateUrl: '#',
  },
  {
    id: 'doc_4',
    employeeId: 'usr_emp_1',
    category: 'Tax Forms',
    name: 'W-4 Withholding / Form 16 Tax Declaration',
    fileName: 'TaxDeclaration_FY2025_2026.pdf',
    fileSize: '890 KB',
    uploadDate: '2026-04-10',
    version: 'v1.0',
    uploaderName: 'David Miller',
    privateUrl: '#',
  },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'ann_1',
    title: 'All-Hands Product Launch & Q3 Milestone Celebration',
    content: 'Team, our Q3 enterprise beta is officially deploying next Friday. Excellent work by Engineering and Design. We will host a company celebration and review our growth targets!',
    authorName: 'Sarah Jenkins (Founder)',
    publishTime: '2026-09-07 10:00 AM',
    priority: 'urgent',
    acknowledgedUserIds: ['usr_emp_1', 'usr_emp_2'],
  },
  {
    id: 'ann_2',
    title: 'Updated Health Benefits & Wellness Stipend Policy',
    content: 'Please review the updated medical coverage handbook in your Document Center. Annual wellness stipends are now active for reimbursement.',
    authorName: 'Sarah Jenkins (Founder)',
    publishTime: '2026-09-01 09:30 AM',
    priority: 'important',
    acknowledgedUserIds: ['usr_emp_1'],
  },
];

export const initialMessages: Message[] = [
  {
    id: 'msg_1',
    conversationId: 'conv_founder_emp1',
    senderId: 'usr_founder',
    recipientId: 'usr_emp_1',
    content: 'Hi David, how is the MFA integration progressing? Client security audit is on the 15th.',
    timestamp: '2026-09-08 14:20',
    read: true,
  },
  {
    id: 'msg_2',
    conversationId: 'conv_founder_emp1',
    senderId: 'usr_emp_1',
    recipientId: 'usr_founder',
    content: 'Going smoothly! The backend TOTP validation is done. I am finishing the recovery codes vault now.',
    timestamp: '2026-09-08 14:25',
    read: true,
  },
  {
    id: 'msg_3',
    conversationId: 'conv_founder_emp1',
    senderId: 'usr_founder',
    recipientId: 'usr_emp_1',
    content: 'Awesome. Once done, let us do a quick walkthrough before merging into staging.',
    timestamp: '2026-09-08 14:30',
    read: false,
  },
];

export const initialRoadmapItems: RoadmapItem[] = [
  {
    id: 'rdm_1',
    title: 'Enterprise Multi-Tenant Isolation & Custom Subdomains',
    description: 'Allow client organizations to run on custom subdomains (e.g. client.hrm.io) with strict database isolation.',
    targetDate: '2026-10-15',
    priority: 'high',
    status: 'in_progress',
    notes: 'Architecture approved; infrastructure provisioning underway.',
    updatedAt: '2026-09-06',
    updatedBy: 'Sarah Jenkins',
  },
  {
    id: 'rdm_2',
    title: 'Automated Payroll & Tax Document Generator',
    description: 'One-click generation of monthly payslips and tax withholding summaries directly into Document Center.',
    targetDate: '2026-11-01',
    priority: 'medium',
    status: 'planned',
    notes: 'Requires coordination with external payroll compliance guidelines.',
    updatedAt: '2026-09-02',
    updatedBy: 'Sarah Jenkins',
  },
  {
    id: 'rdm_3',
    title: 'Real-Time WebSockets Messaging System',
    description: 'Upgrade internal 1-on-1 messenger with live typing indicators and instant push notifications.',
    targetDate: '2026-11-20',
    priority: 'medium',
    status: 'planned',
    notes: 'Assigned for Phase 3 engineering sprint.',
    updatedAt: '2026-09-01',
    updatedBy: 'Sarah Jenkins',
  },
  {
    id: 'rdm_4',
    title: 'SOC2 Type II Compliance & External Penetration Test',
    description: 'Mandatory third-party audit of role-based authorization, private document storage, and finance security.',
    targetDate: '2026-12-10',
    priority: 'high',
    status: 'planned',
    notes: 'Audit firm shortlisted.',
    updatedAt: '2026-08-25',
    updatedBy: 'Sarah Jenkins',
  },
];

export const initialFinanceTransactions: FinanceTransaction[] = [
  {
    id: 'ft_1',
    type: 'inflow',
    date: '2026-09-02',
    amount: 34500,
    category: 'Enterprise SaaS Contract',
    description: 'Annual platform license fee - Client Horizon Systems',
    reference: 'INV-2026-891',
    creatorName: 'Sarah Jenkins',
  },
  {
    id: 'ft_2',
    type: 'inflow',
    date: '2026-09-05',
    amount: 18000,
    category: 'Custom Implementation',
    description: 'Dedicated setup & white-label customization retainer',
    reference: 'INV-2026-892',
    creatorName: 'Sarah Jenkins',
  },
  {
    id: 'ft_3',
    type: 'outflow',
    date: '2026-09-03',
    amount: 4200,
    category: 'Cloud Infrastructure & Hosting',
    description: 'AWS Production Cluster & S3 private document vault monthly billing',
    reference: 'AWS-993821',
    creatorName: 'Sarah Jenkins',
  },
  {
    id: 'ft_4',
    type: 'outflow',
    date: '2026-09-06',
    amount: 2850,
    category: 'Software Tooling & Licences',
    description: 'GitHub Enterprise, Figma, and Datadog APM subscriptions',
    reference: 'SAAS-4412',
    creatorName: 'Sarah Jenkins',
  },
  {
    id: 'ft_5',
    type: 'investment',
    date: '2026-08-15',
    amount: 25000,
    category: 'Hardware Infrastructure',
    description: 'High-performance AI development workstations & on-prem security appliance',
    reference: 'CAPEX-2026-04',
    creatorName: 'Sarah Jenkins',
  },
];

export const initialGrowthMetrics: GrowthMetric[] = [
  { period: 'May 2026', revenue: 42000, burnRate: 18000, netMargin: 24000, growthPercentage: 12.5 },
  { period: 'Jun 2026', revenue: 49500, burnRate: 19500, netMargin: 30000, growthPercentage: 17.8 },
  { period: 'Jul 2026', revenue: 58000, burnRate: 21000, netMargin: 37000, growthPercentage: 17.1 },
  { period: 'Aug 2026', revenue: 68500, burnRate: 22400, netMargin: 46100, growthPercentage: 18.1 },
  { period: 'Sep 2026 (MTD)', revenue: 52500, burnRate: 12800, netMargin: 39700, growthPercentage: 21.4 },
];

export const initialBalanceSheet: BalanceSheetEntry[] = [
  // Current Assets
  {
    id: 'bs_1',
    period: 'Q3 2026',
    category: 'Current Assets',
    lineItem: 'Cash & Cash Equivalents (Operating Bank Account)',
    openingValue: 185000,
    movementValue: 48500,
    closingValue: 233500,
    notes: 'Operating account balances across Silicon Valley Bank & Chase',
  },
  {
    id: 'bs_2',
    period: 'Q3 2026',
    category: 'Current Assets',
    lineItem: 'Accounts Receivable (Invoiced Client Contracts)',
    openingValue: 42000,
    movementValue: 10500,
    closingValue: 52500,
    notes: 'Net 30 invoice settlements due by end of month',
  },
  // Non-Current Assets
  {
    id: 'bs_3',
    period: 'Q3 2026',
    category: 'Non-Current Assets',
    lineItem: 'Technical Equipment & Server Infrastructure',
    openingValue: 45000,
    movementValue: 25000,
    closingValue: 70000,
    notes: 'Includes newly capitalized GPU workstations and network nodes',
  },
  // Current Liabilities
  {
    id: 'bs_4',
    period: 'Q3 2026',
    category: 'Current Liabilities',
    lineItem: 'Accounts Payable & Vendor Obligations',
    openingValue: 14000,
    movementValue: 2200,
    closingValue: 16200,
    notes: 'Cloud hosting and external legal retainer bills',
  },
  // Equity
  {
    id: 'bs_5',
    period: 'Q3 2026',
    category: 'Equity',
    lineItem: 'Retained Earnings & Contributed Capital',
    openingValue: 258000,
    movementValue: 81800,
    closingValue: 339800,
    notes: 'Cumulative operating surplus reinvested into company reserves',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'aud_1',
    user: 'Sarah Jenkins (Founder)',
    action: 'CREATE_TASK',
    entity: 'Task',
    entityId: 'tsk_101',
    changeSummary: 'Assigned "Migrate Core Auth to MFA" to David Miller (Priority: High)',
    timestamp: '2026-09-01 10:15',
  },
  {
    id: 'aud_2',
    user: 'Sarah Jenkins (Founder)',
    action: 'RECORD_FINANCE',
    entity: 'FinanceTransaction',
    entityId: 'ft_1',
    changeSummary: 'Recorded Inflow: $34,500 from Horizon Systems (Enterprise SaaS)',
    timestamp: '2026-09-02 11:30',
  },
  {
    id: 'aud_3',
    user: 'David Miller (Employee)',
    action: 'UPDATE_TASK_PROGRESS',
    entity: 'Task',
    entityId: 'tsk_101',
    changeSummary: 'Updated progress to 65% with status update notes',
    timestamp: '2026-09-08 11:30',
  },
];
